### ISSUE TITLE
The reference to start.xml is different.

### ISSUE THREAD

**Issue by mamesuke88** [stressboi/splunk_wineventcode_secanalysis#10]
splunk_wineventcode_secanalysis/default/data/ui/views/start.xml

When you click on the link, the app ""splunk_wineventcode_secanalysis" is not available" because the reference is different.

please fix "<a href="../splunk_wineventcode_secanalysis/ ..." to "<a href="../splunk_wineventcode_secanalysis-master/ ..." 

https://github.com/stressboi/splunk_wineventcode_secanalysis/blob/235df9325b5692285507c4ed12d6324b016360db/default/data/ui/views/start.xml#L113
https://github.com/stressboi/splunk_wineventcode_secanalysis/blob/235df9325b5692285507c4ed12d6324b016360db/default/data/ui/views/start.xml#L130
https://github.com/stressboi/splunk_wineventcode_secanalysis/blob/235df9325b5692285507c4ed12d6324b016360db/default/data/ui/views/start.xml#L149
https://github.com/stressboi/splunk_wineventcode_secanalysis/blob/235df9325b5692285507c4ed12d6324b016360db/default/data/ui/views/start.xml#L167

**Comment by stressboi** [comment]
@mamesuke88 you have downloaded the app directly from the repo and not removed the "-master" that is added because this is all in the master branch. The app name should be "splunk_wineventcode_secanalysis" - rename it that in the filesystem, please. Or, download the .spl version in this repo.

**Comment by mamesuke88** [comment]
Thank you for the reply.
This app is very useful and appreciated!
