### ISSUE TITLE
Enhancement Request: Please add wildcard index selection

### ISSUE THREAD

**Issue by afxmac** [stressboi/splunk_wineventcode_secanalysis#4]
Hi,
this looks cool! But thanks to our access control requirements, we have many windows indexes that should be included. Thankfully that could be done via a wildcard. So in addition or instead of having index dropdowns, a wildcard selection would be very much appreciated.
thx
afx

**Comment by stressboi** [comment]
@afxmac I can certainly add - give me a bit! Thanks.

**Comment by stressboi** [comment]
@afxmac completed - see latest update.
