### ISSUE TITLE
ER - Ability to select OR for WinEventLog and XmlWinEventLog

### ISSUE THREAD

**Issue by inspired** [stressboi/splunk_wineventcode_secanalysis#8]
Hi James,

During a workshop today I was asked why we can't select both sourcetypes at the same time in the dashboard **individual_event_code_analysis** . I realize editing the Dashboard would make it possible.

I'm thinking this would be useful as an organization may have some hosts logging in Classic format and others in XML.

**Comment by stressboi** [comment]
Good comment, that somehow I missed when you posted it. Let me review.

**Comment by stressboi** [comment]
Resolved in version 1.5.1
